services:
  postgres:
    image: postgres:16
    container_name: dkpdb
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DATABASE: ${POSTGRES_DATABASE}
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  wait-for-postgres:
    image: busybox:1.31.1
    depends_on:
      postgres:
        condition: service_healthy
    entrypoint: ["sh", "-c", "while ! nc -z postgres 5432; do sleep 1; done;"]

volumes:
  postgres_data:
